<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/26plotly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import plotly.express as px
import pandas as pd

In [3]:
student = pd.read_csv('/content/students.csv')
student

,student_id,student_name,gender,age,hours_studied,marks,subject,attendance_percentage,previous_gpa
0,1,Alice Johnson,Female,18,5.5,78,Math,85,3.2
1,2,Bob Smith,Male,19,8.2,92,Math,92,3.8
2,3,Charlie Brown,Male,18,3.5,55,Science,70,2.5
3,4,Diana Prince,Female,19,9.1,95,Science,98,4.0
4,5,Edward Lee,Male,20,6.8,82,English,88,3.4
...,...,...,...,...,...,...,...,...,...
125,126,Yum Lee,Female,20,6.5,79,English,85,3.4
126,127,Zed Murphy,Female,19,7.1,84,English,88,3.5
127,128,Ace Price,Female,18,3.8,55,Math,65,2.4
128,129,Bod Brooks,Female,20,8.5,91,Math,93,3.8
129,130,Cid Cox,Male,19,5.0,69,Science,75,3.0

In [9]:
fig = px.scatter(student, x = 'hours_studied', y = 'marks', color = 'gender',size = 'previous_gpa', hover_data=['hours_studied', 'marks', 'subject'])
fig.show()

In [10]:
enrollment = pd.read_csv('/content/enrollment_data.csv')
enrollment

   Year  Programming  Digital Marketing
0  2015          589                734
1  2016          862                963
2  2017         1085               1157
3  2018         1150               1404
4  2019         1439               1497
5  2020         1715               1579
6  2021         1785               1948
7  2022         1995               2073
8  2023         2236               2310
9  2024         2442               2338

In [12]:
fig = px.line(enrollment, x = 'Year', y = 'Programming', markers = True)
fig.show()

In [13]:
fig.write_html('Programming_data.html')

In [15]:
fig = px.histogram(student, x = 'attendance_percentage', color = 'gender')
fig.show()

In [16]:
fig = px.histogram(student, x = 'attendance_percentage', color = 'gender', nbins = 5)
fig.show()